###
GET http://localhost:8080/api/user/search?user=user1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzM1OCwiZXhwIjoxNzA1OTI4MTU4fQ.6-IK4NAPu706bdKqnkqDj_iEF-c0Aw2AaqrWmZgMi1Q

###
POST http://localhost:8080/api/user/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
Content-Type: application/json

{
  "userFollowedId": 3
}

###
DELETE http://localhost:8080/api/user/unfollow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcwNTMyMzY0NSwiZXhwIjoxNzA1OTI4NDQ1fQ.cnvLtWFSNFW3_ElVm1dKlRmIiURHauNb5QyakLmWZYY
Content-Type: application/json

{
  "userFollowedId": 1
}

###
GET http://localhost:8080/api/user/followers-stats
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcwNTMyMzY0NSwiZXhwIjoxNzA1OTI4NDQ1fQ.cnvLtWFSNFW3_ElVm1dKlRmIiURHauNb5QyakLmWZYY

###
GET http://localhost:8080/api/user/followers?page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcwNTMyMzY0NSwiZXhwIjoxNzA1OTI4NDQ1fQ.cnvLtWFSNFW3_ElVm1dKlRmIiURHauNb5QyakLmWZYY

###
GET http://localhost:8080/api/user/following?page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcwNTMyMzY0NSwiZXhwIjoxNzA1OTI4NDQ1fQ.cnvLtWFSNFW3_ElVm1dKlRmIiURHauNb5QyakLmWZYY

###
GET http://localhost:8080/api/user/profile?user=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcwNTMyMzY0NSwiZXhwIjoxNzA1OTI4NDQ1fQ.cnvLtWFSNFW3_ElVm1dKlRmIiURHauNb5QyakLmWZYY

###
PUT http://localhost:8080/api/user/username
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTcwNTMyMzY0NSwiZXhwIjoxNzA1OTI4NDQ1fQ.cnvLtWFSNFW3_ElVm1dKlRmIiURHauNb5QyakLmWZYY
Content-Type: application/json

{
  "newUsername": "Albert"
}

###
PUT http://localhost:8080/api/user/email
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGJlcnQiLCJpYXQiOjE3MDUzMjM4NDUsImV4cCI6MTcwNTkyODY0NX0.Z11ID8g4Q0ggJEE4OFOfBbOvWlcT3BUx0oKywxQ-tXU
Content-Type: application/json

{
  "newEmail": "albert@email.com"
}

###
PUT http://localhost:8080/api/user/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGJlcnQiLCJpYXQiOjE3MDUzMjM4NDUsImV4cCI6MTcwNTkyODY0NX0.Z11ID8g4Q0ggJEE4OFOfBbOvWlcT3BUx0oKywxQ-tXU
Content-Type: application/json

{
  "currentPassword": "password",
  "newPassword": "passwordForAlbert"
}

###
DELETE http://localhost:8080/api/user/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGJlcnQiLCJpYXQiOjE3MDUzMjM4NDUsImV4cCI6MTcwNTkyODY0NX0.Z11ID8g4Q0ggJEE4OFOfBbOvWlcT3BUx0oKywxQ-tXU
Content-Type: application/json

{
  "password": "passwordForAlbert"
}
