###
# Should return a list of albums that match the search term
GET http://localhost:8080/api/album/search?album=nevermind

<> 2023-09-30T183318.200.json

###
# Should return a specific album
GET http://localhost:8080/api/album/info?album=nevermind&artist=nirvana
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzM1OCwiZXhwIjoxNzA1OTI4MTU4fQ.6-IK4NAPu706bdKqnkqDj_iEF-c0Aw2AaqrWmZgMi1Q