###
POST http://localhost:8080/api/later-listen
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
Content-Type: application/json

{
  "albumId": 1
}

###
DELETE http://localhost:8080/api/later-listen
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
Content-Type: application/json

{
  "albumId": 1
}

###
GET http://localhost:8080/api/later-listen/my-later-listens
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
