###
POST http://localhost:8080/api/review
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
Content-Type: application/json

{
  "albumId": 1,
  "text": "Test review"
}

###
PUT http://localhost:8080/api/review
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
Content-Type: application/json

{
  "albumId": 1,
  "text": "Excellent"
}

###
DELETE http://localhost:8080/api/review
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
Content-Type: application/json

{
  "albumId": 1
}

###
GET http://localhost:8080/api/review/my-reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I

###
GET http://localhost:8080/api/review/users-latest?user=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I

###
GET http://localhost:8080/api/review/friends-latest?page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTcwNTMyMzkyNywiZXhwIjoxNzA1OTI4NzI3fQ.fRbCPJGi7rNCM1LaS9PuYq12nrSdWISrtOLeTzzsS8I
